apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: argo-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: argo
    spec:
      containers:
      - name: nginx
        image: nginx
